version: 0.0
os: linux
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 80
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 30
      runas: root



