version: 0.2
env:
  parameter-store:
    JASYPT_KEY: "/test/web-server/jasypt-key"

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - gradle clean build -Pspring.profiles.active=dev -Pjasypt.encryptor.password=$(echo JASYPT_KEY)
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/flower-platform.jar
    - appspec.yml
    - start_server.sh
    - stop_server.sh
    - validate_service.sh
  discard-paths: yes