version: 0.2
env:
  parameter-store:
    JASYPT_KEY: "/test/web-server/jasypt-key"

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - echo $JASYPT_KEY
      - gradle clean build -Pspring.profiles.active=dev -Pjasypt.encryptor.password=$JASYPT_KEY
  post_build:
    commands:
      - echo Build completed on `date`
      - touch jasyptKey.txt
      - touch dbEndpoint.txt
      - echo -n $JASYPT_KEY > jasyptKey.txt
      - echo -n "jdbc:mysql://$(aws cloudformation describe-stacks --stack-name test-env --query "Stacks[0].Outputs[?OutputKey=='RdsDbEndpoint'].OutputValue" --output text):3306/flower_platform" > dbEndpoint.txt
artifacts:
  files:
    - build/libs/flower-platform.jar
    - dbEndpoint.txt
    - appspec.yml
    - start_server.sh
    - stop_server.sh
    - validate_service.sh
    - jasyptKey.txt
    - allow_traffic.sh
    - after_install.sh
  discard-paths: yes